#!/usr/bin/env bash
set -euo pipefail

# ./run install
if [ "$1" == "install" ]; then
    python3 -m pip install --user -r requirements.txt
    exit 0

# ./ run test
elif [ "$1" == "test" ]; then
    python3 -m pytest
    exit 0

# ./ run URL_FILE
else
    URL_FILE="$1"
    if [ ! -f "$URL_FILE" ]; then
        echo "Error: File not found: $URL_FILE"
        exit 1
    fi
    python3 src/scorer/cli_updated.py "$URL_FILE"
    exit 0
fi